version: "3.7"

services: 
   queuebackend:
        image: 'node-webapp9'
        ports:
            - 5000:5000
        command: ["node", "index.js"]
        depends_on:
            - db
        environment:
            - DATABASE_URL = postgres://kkosyrgi:zrn-y1rBMUGZbBj9WgEbWMPjZrrhcG5a@ruby.db.elephantsql.com:5432/kkosyrgi
            - PORT = 5000
    queuefrontend: 
        image: 'react-webapp'
        ports: 
            - 5000:5000
        command: ["npm", "start"]
    db:
        image: 'postgress: latest'
        environment:
            - POSTGRES_USER=kkosyrgi 
            - POSTGRES_PASSWORD=zrn-y1rBMUGZbBj9WgEbWMPjZrrhcG5a
            - POSTGRES_DB=kkosyrgi 
        ports:
            - "5432:5432"